### PR TITLE
C and Fortran API for Interpolator

### LINKED ISSUE #177: Failing `test_normalization_routine`
I have found this interesting bug causing the `test/test_normalisation.cpp` to fail. As demonstrated below, it can pass or fail if run multiple times. I am on life with Kokkos Serial/OpenMP backend. I am using kokkos and kokkos-kernel master branches. The log when failing is attached.

[pcms_norm_test.log](https://github.com/user-attachments/files/20277459/pcms_norm_test.log)

```
hasanm4@life:pcms$ ctest -R "test_normalization_routine"
Test project /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms
    Start 20: test_normalization_routine
1/1 Test #20: test_normalization_routine .......   Passed    0.07 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.13 sec
hasanm4@life:pcms$ ctest -R "test_normalization_routine"
Test project /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms
    Start 20: test_normalization_routine
1/1 Test #20: test_normalization_routine .......   Passed    0.26 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.31 sec
hasanm4@life:pcms$ ctest -R "test_normalization_routine"
Test project /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms
    Start 20: test_normalization_routine
1/1 Test #20: test_normalization_routine .......***Failed    0.06 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.12 sec

The following tests FAILED:
         20 - test_normalization_routine (Failed)
Errors while running CTest
Output from these tests are in: /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
[ble: exit 8]
hasanm4@life:pcms$ ctest -R "test_normalization_routine"
Test project /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms
    Start 20: test_normalization_routine
1/1 Test #20: test_normalization_routine .......   Passed    0.27 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.59 sec
hasanm4@life:pcms$ ctest -R "test_normalization_routine"
Test project /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms
    Start 20: test_normalization_routine
1/1 Test #20: test_normalization_routine .......***Failed    0.06 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.11 sec

The following tests FAILED:
         20 - test_normalization_routine (Failed)
Errors while running CTest
Output from these tests are in: /lore/hasanm4/wsources/DEGAS2-XGC/PCMS/builds/NATIVE/pcms/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

### LINKED ISSUE #207: RBF Interpolated Values Look Off
I was trying to fix the [Interpolation Class Test](https://github.com/Fuad-HH/pcms/blob/mergecfortapi/test/test_interpolation_class.cpp) that I am adding in #178 and found that the interpolated values look incorrect. The idea of the test is that I start by calculating `sin(x) cos(y) + 1` for the node coordinates (top). Then I average the node values to the centroids (bottom middle). Then I tried to interpolate back from the centroids to the nodes using the RBF interpolation. I tried both the adjacency-based search method (bottom left) and my pointcloud-based (n-squared) search method (bottom right) to interpolate the centroid values to the nodes. The two pictures are for 10 by 10 and 20 by 20 element cases, respectively.

I did not make them use the same scale to show that the "trend/shape" of the field remains the same, but the values are lower everywhere. My initial concern is, even though the field can get averaged out, how can it get lower than 1 everywhere?

Image

Image

### PR DESCRIPTION
**Pull request by Fuad-HH**
- [x] API
- [x] Test API
- [x] More parameters for controlling interpolator behavior
- [x] Remove hardcoded parameters and prints
- [x] Fix #177 
- [x] Fix `test_normalization_routine`
- [x] Fix other interpolation tests
- [x] Fix #207 
- [x] Fix the test_interpolation_on_ltx_mesh
- [x] Virtual destructor for interpolator base
- [x] Merge APIs for Point Cloud-based and MLS
- [x] Add file and method documentation
- [x] Merge omega_h handle pointer

### CODE REVIEW

File: src/pcms/capi/interpolator.cpp [hunk 1]
```diff
@@ -27,6 +27,73 @@ PcmsPointBasedInterpolatorHandle pcms_create_point_based_interpolator(void* sour
...
+  // then, create a point based interpolator like above
+  auto xgc_fname = std::string(xgc_mesh_filename);
+  auto dg2_fname = std::string(dg2_mesh_filename);
+
+  // trim the filenames since they are coming from c or fortran api which may have extra spaces at the end
+  xgc_fname = xgc_fname.erase(xgc_fname.find_last_not_of(" \n\r\t")+1);
+  dg2_fname = dg2_fname.erase(dg2_fname.find_last_not_of(" \n\r\t")+1);
+  printf("The interpolator got xgc mesh file: %s and dg2 mesh file: %s\n", xgc_fname.c_str(), dg2_fname.c_str());
+
+  // read the meshes
```
[the remark this answers is not in the document]
Comment (jacobmerson) [reply src/pcms/capi/interpolator.cpp:43]: This may be a question for @cwsmith if Omega_h supports having two separate meshes in parallel in the same library.

File: src/pcms/interpolator/interpolation_base.cpp [hunk 2]
```diff
@@ -153,6 +153,8 @@ void MLSPointCloudInterpolation::find_supports(uint min_req_supports)
   uint min_supports_found = 0;
   uint max_supports_found = 0;
   // radius adjustment loop
+  int loop_count = 0;
+  int max_count = 100;
```
[the remark this answers is not in the document]
Comment (jacobmerson) [reply src/pcms/interpolator/interpolation_base.cpp:155]: Sounds good. It's marked as draft anyways I just wanted to provide some feedback while I had time.

File: src/pcms/capi/interpolator.h [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+  const char* xgc_mesh_filename, const char* dg2_mesh_filename, double radius,
+  int degree, int min_req_supports, double lambda, double decay_factor);
+PcmsPointBasedInterpolatorHandle pcms_create_degas2xgcnode_interpolator(
+  void* target_points, int target_points_size, const char* dg2_mesh_filename,
+  double radius, void* dg2_elem_count, int degree, int min_req_supports,
+  double lambda, double decay_factor);
+PcmsPointBasedInterpolatorHandle pcms_create_xgcnodedegas2_interpolator(
+  const char* dg2_mesh_filename, void* source_points, int source_points_size,
+  double radius, void* dg2_elem_count, int degree, int min_req_supports,
+  double lambda, double decay_factor);
```
Comment (jacobmerson) [inline src/pcms/capi/interpolator.h]: I don't think most of the internal interpolation routines should be specific to degas2/xgc. I'd rather that we have a reader that creates a field handle for xgc and degas2 that can be directly used with the more general interpolation APIs.

File: src/pcms/interpolator/interpolation_base.cpp [hunk 4]
```diff
@@ -0,0 +1,463 @@
...
+        radii2_l[i] *= factor;
+      } else if (nsupports > max_allowed_supports) { // if too many supports
+        double factor =
+          Omega_h::Real(min_req_supports) / Omega_h::Real(nsupports);
+        OMEGA_H_CHECK_PRINTF(factor < 1.0,
+                             "Factor should be less than 1.0: %f\n", factor);
+        factor = (factor < 0.1) ? 0.33 : factor;
+        radii2_l[i] *= factor;
+      }
+      num_supports[i] = 0; // reset the support pointer
```
[the remark this answers is not in the document]
Comment (jacobmerson) [reply src/pcms/interpolator/interpolation_base.cpp]: I'm not sure that I have a good solution here in terms of how to pick that factor for searching. @MohammadElahiNU did implement the uniform grid search with a circle/sphere that should increase the speed of the search for points only in https://github.com/SCOREC/pcms/pull/176 .

However, that pull request never got merged because it had a bunch of duplicated code that needs to get cleaned up. Mohammad is mostly working on other stuff and we didn't have a chance to get back to it.

File: src/pcms/capi/CMakeLists.txt [hunk 5]
```diff
@@ -19,8 +19,22 @@ set_target_properties(
...
+add_library(pcms::interpolator::capi ALIAS pcms_interpolator_capi)
+target_link_libraries(pcms_interpolator_capi PUBLIC MPI::MPI_C PRIVATE pcms::interpolator)
+target_include_directories(pcms_interpolator_capi
+        PUBLIC
+        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../..>" # this makes the module path cpms/capi
+        "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/pcms/capi>")
+set(INT_CAPI_HEADERS ${CMAKE_CURRENT_SOURCE_DIR}/interpolator.h)
+set_target_properties(pcms_interpolator_capi
+  PROPERTIES PUBLIC_HEADERS "${INT_CAPI_HEADERS}"
+             OUTPUTNAME pcmsinterpolatorcapi
```
[the remark this answers is not in the document]
Comment (jacobmerson) [reply src/pcms/capi/CMakeLists.txt]: Indeed, `OUTPUT_NAME` is correct: https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#target-properties

File: src/pcms/capi/interpolator.cpp [hunk 6]
```diff
@@ -0,0 +1,241 @@
+//
+// Created by hasanm4 on 2/17/25.
+//
+#include <pcms/capi/kokkos.h>
+#include "interpolator.h"
+#include <interpolation_base.h>
```
Comment (jacobmerson) [inline src/pcms/capi/interpolator.cpp]: use full path

File: src/pcms/capi/interpolator.cpp [hunk 7]
```diff
@@ -0,0 +1,241 @@
...
+{
+  if (pointer) {
+    int* dg2_elem_count_int = reinterpret_cast<int*>(pointer);
+    *dg2_elem_count_int = value;
+  } else {
+    pcms::printError("Error: NULL pointer provided to write integer value\n");
+  }
+}
+
+PcmsPointBasedInterpolatorHandle pcms_create_degas2xgcnode_interpolator(
```
Comment (jacobmerson) [inline src/pcms/capi/interpolator.cpp]: is this a case we currently need to support?

File: src/pcms/interpolator/interpolation_base.h [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+    Omega_h::Write<Omega_h::Real> radii2_l,
+    Omega_h::Write<Omega_h::LO> num_supports) const;
+  void find_supports(uint min_req_supports = 10, uint max_allowed_supports = 30,
+                     uint max_count = 100);
+};
+
+/**
+ * @brief Moving Least Square Radial Basis Function Interpolation
+ */
+class MLSInterpolationHandler : public InterpolationBase
```
Comment (jacobmerson) [inline src/pcms/interpolator/interpolation_base.h]: There may be an opportunity to join with `MLSPointCloudInterpolator`? It seems like most things besides the search should be the same.

If not, we need to rename this. I don't know what `Handler` means. Maybe `MLSMeshInterpolator`?

File: src/pcms/interpolator/interpolation_base.h [hunk 9]
```diff
@@ -0,0 +1,142 @@
...
+  Omega_h::Mesh& target_mesh_;
+  Omega_h::Reals source_coords_;
+  Omega_h::Reals target_coords_;
+
+  SupportResults supports_;
+
+  Omega_h::HostWrite<Omega_h::Real> target_field_;
+  Omega_h::HostWrite<Omega_h::Real> source_field_;
+
+  void find_supports(uint min_req_supports = 10);
```
Comment (jacobmerson) [inline src/pcms/interpolator/interpolation_base.h]: Maybe a baseclass for the search would help us combine things?

File: src/pcms/interpolator/interpolation_base.cpp [hunk 10]
```diff
@@ -0,0 +1,463 @@
...
+  // copy the support index to the supports
+  supports_.radii2 = radii2_l;
+  supports_.supports_ptr = Omega_h::LOs(support_ptr_l);
+  supports_.supports_idx = Omega_h::LOs(support_idx_l);
+}
+
+void MLSPointCloudInterpolation::distance_based_pointcloud_search(
+  Omega_h::Write<Omega_h::Real> radii2_l,
+  Omega_h::Write<Omega_h::LO> num_supports) const
+{
```
Comment (jacobmerson) [inline src/pcms/interpolator/interpolation_base.cpp]: Add note to use search structure once https://github.com/SCOREC/pcms/pull/176 is merged.

File: src/pcms/interpolator/interpolation_base.cpp [hunk 11]
```diff
@@ -0,0 +1,463 @@
...
+  pcms::Rank1View<double, pcms::HostMemorySpace> target_field)
+{
+  OMEGA_H_CHECK_PRINTF(target_field.size() == target_coords_.size() / dim_,
+                       "Source Data and Source Points size mismatch: %zu %d\n",
+                       target_field.size(), target_coords_.size() / dim_);
+
+  OMEGA_H_CHECK_PRINTF(source_field.size() == source_coords_.size() / dim_,
+                       "Target Data and Target Points size mismatch: %zu %d\n",
+                       source_field.size(), source_coords_.size() / dim_);
+  for (int i = 0; i < 10; i++) {
```
Comment (jacobmerson) [inline src/pcms/interpolator/interpolation_base.cpp]: this looks like some debug printing. I think it should be removed, or at least only printed in a debug mode.

File: src/pcms/capi/interpolator.cpp (hunk 7 above)
Comment (Fuad-HH) [reply src/pcms/capi/interpolator.cpp]: Yes, I use this because in Degas2 XGC coupling, we need to transfer data from Degas2 centroids XGC nodes. Used [here](https://github.com/Fuad-HH/XGC-Devel/blob/8d910ec8b0f850a96e9c72e546b2dc22116ef572/XGC_core/neutral_totalf.F90#L895).

File: src/pcms/capi/interpolator.h [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+extern "C" {
+#endif
+
+struct PcmsInterpolatorHandle
+{
+  void* pointer;
+};
+typedef struct PcmsInterpolatorHandle PcmsInterpolatorHandle;
+
+struct PcmsPointBasedInterpolatorHandle
```
[the remark this answers is not in the document]
Comment (Fuad-HH) [reply src/pcms/capi/interpolator.h]: Yes, I agree. I could not find a better way to handle this. I am considering using an inherited class with a better virtual class than I currently have. I can work on it.

File: src/pcms/interpolator/interpolation_base.cpp [hunk 13]
```diff
@@ -0,0 +1,463 @@
...
+void copyHostWrite2ScalarArrayView(
+  const Omega_h::HostWrite<Omega_h::Real>& source,
+  pcms::Rank1View<double, pcms::HostMemorySpace> target)
+{
+  OMEGA_H_CHECK_PRINTF(
+    source.size() == target.size(),
+    "Size mismatch in copy_data_from_HostWrite_to_ScalarArray: %d %zu\n",
+    source.size(), target.size());
+
+  for (int i = 0; i < source.size(); ++i) {
```
[the remark this answers is not in the document]
Comment (Fuad-HH) [reply src/pcms/interpolator/interpolation_base.cpp]: Checking with `data_handle` and `data` methods from PCMS and Kokkos, respectively.

File: src/pcms/print.h [hunk 14]
```diff
@@ -43,6 +43,22 @@ KOKKOS_INLINE_FUNCTION void printInfo(const char* fmt, const Args&... args)
...
+  spdlog::debug("{}", fmt::sprintf(fmt, args...));
+#else
+  fprintf(getStdout(), fmt, args...);
+#endif
+#else // For GPU execution
+  printf(fmt, args...);
+#endif
+#endif
+}
+
```
Comment (Fuad-HH) [inline src/pcms/print.h]: I needed it on the GPU too, so I made it a little different than the others here. I think those should have a similar print statement for the GPU, too.

**Comment by Fuad-HH** [comment]
The above commit (https://github.com/SCOREC/pcms/pull/178/commits/4013be7f55701e713517412169aa4ae95b98e681) is failing two tests:
```bash
      Start 15: interpolate linear 2d omega_h_field
15/44 Test #15: interpolate linear 2d omega_h_field ......Subprocess aborted***Exception:   1.98 sec
      Start 16: interpolate quadratic 2d omega_h_field
16/44 Test #16: interpolate quadratic 2d omega_h_field ...Subprocess aborted***Exception:   4.89 sec
```
Although the tests are not failing in the CI/CD.

**Comment by jacobmerson** [comment]
It looks like the test failures that are coming up is related to: https://github.com/SCOREC/meshFields/issues/69

File: src/pcms/print.h [hunk 15]
```diff
@@ -43,6 +43,22 @@ KOKKOS_INLINE_FUNCTION void printInfo(const char* fmt, const Args&... args)
...
+#if defined(PCMS_SPDLOG_ENABLED)
+  spdlog::debug("{}", fmt::sprintf(fmt, args...));
+#else
+  fprintf(getStdout(), fmt, args...);
+#endif
+#else // For GPU execution
+  printf(fmt, args...);
+#endif
+#endif
+}
```
[the remark this answers is not in the document]
Comment (Fuad-HH) [reply src/pcms/print.h]: Removed ` && defined(PCMS_PRINT_ENABLED)` so that it prints in https://github.com/SCOREC/pcms/pull/178/commits/ceb6334cb956f67c32e6e55a3cff29e9e13825b5. Should not depend on `PCMS_PRINT_ENABLED` flag.

File: test/test_interpolation_on_ltx_mesh.cpp [hunk 16]
```diff
@@ -0,0 +1,385 @@
...
+    double x, y, z;
+    line_stream >> node_id >> x >> y >> z;
+
+    if (std::abs(z) > 1e-9 || std::isnan(z)) {
+      // the ltx mesh has some 1.0 in the node file, which is fine
+      if (!((std::abs(z) - 1.0) < 1e-9)) {
+        printf("[WARNING] Non-zero Z coordinate found (%f) for node ID %d. "
+               "Expected Z=0 for 2D mesh.\n",
+               z, node_id);
+      }
```
[the remark this answers is not in the document]
Comment (Fuad-HH) [reply test/test_interpolation_on_ltx_mesh.cpp]: Removed in https://github.com/SCOREC/pcms/pull/178/commits/ce865846f75722cf94022118f748005b2228c1a6.

File: test/test_interpolation_class.cpp [hunk 17]
```diff
@@ -0,0 +1,330 @@
...
+
+    for (int i = 0; i < interpolated_data_hwrite.size(); i++) {
+      pcms::printInfo("Interpolated data: %d, %.16f, %.16f\n", i,
+                      interpolated_data_hwrite[i],
+                      point_cloud_interpolated_data_hwrite[i]);
+
+      REQUIRE_THAT(
+        point_cloud_interpolated_data_hwrite[i],
+        Catch::Matchers::WithinAbs(interpolated_data_hwrite[i], 1e-4));
+    }
```
[the remark this answers is not in the document]
Comment (Fuad-HH) [reply test/test_interpolation_class.cpp]: It's fine. It can be helpful.

File: src/pcms/fortranapi/interpolator.i [hunk 18]
```diff
@@ -0,0 +1,39 @@
+%module pcms_interpolator
+%{
+#include "pcms/capi/interpolator.h"
+#include "pcms/capi/kokkos.h"
+%}
+%include <../external/flibhpc/include/mpi.i>
+%include <stdint.i>
+%include <typemaps.i>
+
+struct PcmsInterpolatorOHMeshHandle
```
Comment (jacobmerson) [inline src/pcms/fortranapi/interpolator.i]: Is there a reason we need a different OmegaH handle than the one that's in the client.h?

Comment (Fuad-HH) [reply src/pcms/fortranapi/interpolator.i]: I was trying to write a test case to demonstrate that if the library goes out of scope before the mesh, the mesh remains intact or not; it looks like it remains intact. I am not sure what's going on there.

File: src/pcms/capi/interpolator.cpp [hunk 19]
```diff
@@ -0,0 +1,155 @@
...
+}
+
+void pcms_destroy_interpolator(PcmsInterpolatorHandle interpolator)
+{
+  if (interpolator.pointer != nullptr) {
+    delete reinterpret_cast<InterpolationBase*>(interpolator.pointer);
+  }
+}
+
+PcmsInterpolatorOHMeshHandle read_oh_mesh(const char* filename)
```
Comment (jacobmerson) [inline src/pcms/capi/interpolator.cpp]: rename to `pcms_create_omega_h_mesh`

File: src/pcms/capi/interpolator.cpp [hunk 20]
```diff
@@ -0,0 +1,155 @@
...
+  // trim the filename since it is coming from c or fortran api which may have
+  // extra spaces at the end
+  fname.erase(fname.find_last_not_of(" \n\r\t") + 1);
+  auto* oh_lib = new Omega_h::Library();
+  auto* mesh = new Omega_h::Mesh(Omega_h::binary::read(fname, oh_lib->world()));
+
+  return {reinterpret_cast<void*>(mesh), reinterpret_cast<void*>(oh_lib)};
+}
+
+void release_oh_mesh(PcmsInterpolatorOHMeshHandle oh_mesh)
```
Comment (jacobmerson) [inline src/pcms/capi/interpolator.cpp]: `destroy_omega_h_mesh`

**Comment by Fuad-HH** [comment]
@jacobmerson, could you please review the changes I made to separate the mesh API to a different header?

However, I could not remove the mesh handle we already have in `client.h`.
I was trying to delete `PcmsOmegaHMeshHandle` and run swig after it. But the `client_wrap.c` file pcms currently has is not up to date with the `client.i` it has there. If I run swig on `client.i`, it changes another definition in the generated `.c` and `.f90` files. This is because the `PcmsClientHandle` has only a member `pointer` in `client.i`:
https://github.com/SCOREC/pcms/blob/a07efb906fa3421acc4b9be4dbfaaa67b8c537ee/src/pcms/fortranapi/client.i#L31-L34
But in `client.h`, it is defined as below
https://github.com/SCOREC/pcms/blob/a07efb906fa3421acc4b9be4dbfaaa67b8c537ee/src/pcms/capi/client.h#L10-L14


And it is producing the following error as expected
```bash
pcms/src/pcms/fortranapi/client_wrap.c:306:21: error: ‘struct PcmsClientHandle’ has no member named ‘pointer’; did you mean ‘appPointer’?
  306 |   if (arg1) (arg1)->pointer = arg2;
      |                     ^~~~~~~
      |                     appPointer
``` 

I think it is better to solve it in a different pull request. I can open an issue for it and solve it pretty quickly later.

File: src/pcms/capi/mesh.h [hunk 21]
```diff
@@ -0,0 +1,82 @@
+#ifndef PCMS_OMEGA_H_MESH_CAPI_H
+#define PCMS_OMEGA_H_MESH_CAPI_H
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+struct PcmsInterpolatorOmega_hLibraryHandle
```
Comment (jacobmerson) [inline src/pcms/capi/mesh.h]: This should be called `PcmsOmegaHLibraryHandle` to have consistent naming.

File: src/pcms/capi/mesh.h [hunk 22]
```diff
@@ -0,0 +1,82 @@
...
+  void* lib_handle;
+};
+typedef struct PcmsInterpolatorOmega_hLibraryHandle
+  PcmsInterpolatorOmega_hLibraryHandle;
+
+/**
+ * @brief Holds void pointers of Omega_h Mesh object and the library
+ * (communicator) handle
+ */
+struct PcmsInterpolatorOmega_hMeshHandle
```
Comment (jacobmerson) [inline src/pcms/capi/mesh.h]: This should be called PcmsOmegaHMeshHandle to have consistent naming.

**Review by jacobmerson — CHANGES_REQUESTED** [review]
One more pedantic change to make the naming scheme consistent, but otherwise I'm ready to merge this.

**Comment by Fuad-HH** [comment]
Thank you. Renamed.

**Review by jacobmerson — APPROVED** [review]

**Comment by jacobmerson** [comment]
last time that ltx interpolation test was failing it was due to a check with too tight of a tolerance in meshFields. I'm wondering if the version specified for meshFields in #231 was before that was fixed...looking into it.

**Comment by jacobmerson** [comment]
Everything is working locally with my own build. I'm going to try to run in ACT on my local system so I can go into the docker container and get more insight into what's going on. Current working theory is that the testdata repo is out of date for some reason.

I most likely won't be able to get back to this until tomorrow.

**Comment by Fuad-HH** [comment]
Looks like there's an issue reading the mesh in the test. Looking at the `build-Omega_h` phase of this latest [Test-Build](https://github.com/SCOREC/pcms/actions/runs/20071984159/job/57576355944?pr=178), I found that it is using Omega_h commit https://github.com/SCOREC/omega_h/commit/fbe1cc131fb1b5ac840129ecd8bd7b42ab244000. This commit has an issue reading this specific mesh used in this test case. It was fixed on the next commit. Could you please use the latest commit of Omega_h?

The reading issue is described in https://github.com/SCOREC/omega_h/issues/183 and was fixed in https://github.com/SCOREC/omega_h/pull/184. It worked before because you cleared the cache before, and Omega_h was using the latest commit with the fix.  

For instance, the [last passing test job](https://github.com/SCOREC/pcms/actions/runs/19979021878/job/57301669015) above was using https://github.com/SCOREC/omega_h/commit/d1f09bb610b20e3c613b506149ab8df1e1a7b43f, which includes the abovementioned pull request. My guess is that https://github.com/SCOREC/pcms/pull/231 specifies Omega_h version to be scorec-v11.0.0. It does not include the mesh reader fix.

**Comment by Fuad-HH** [comment]
Thanks. The test is passing. The installation is failing here. But locally, for me, it is working. I am trying to sort it out.

**Comment by jacobmerson** [comment]
Looks like that new test case for installations is paying off! :)

My guess is it has something to do with the fact that you have `pcms::interpolator::capi`. When I look in the `pcms_capi-targets.cmake` it has `pcms::interpolatorcapi`.

**Comment by jacobmerson** [comment]
@Sichao25 @cwsmith any ideas on why this might be failing? It's working locally by running the test installation (albeit with a different version of CMake).

**Comment by Sichao25** [comment]
Maybe we can try to put `include("${CMAKE_CURRENT_LIST_DIR}/pcms_interpolator-targets.cmake")` before capi targets in `config.cmake.in`?

**Comment by jacobmerson** [comment]
> Maybe we can try to put `include("${CMAKE_CURRENT_LIST_DIR}/pcms_interpolator-targets.cmake")` before capi targets in `config.cmake.in`?

That's a solid theory. Let me give it a try.

@Sichao25 it worked! thanks
